"""
LangGraph workflow for DramaType Agent.

Builds a stateful graph with nodes for each pipeline step.
Can run in rule_based, llm, or rag mode.
"""

import json
from pathlib import Path

from app.agent.state import DramaTypeAgentState


# ── Node functions ─────────────────────────────────────

def read_material_node(state: DramaTypeAgentState) -> dict:
    """Read the material markdown file."""
    from app.agent.material_parser import read_material
    from app.core.paths import DEFAULT_INPUT_PATH

    material_text = read_material(DEFAULT_INPUT_PATH)
    return {"material_text": material_text}


def parse_material_node(state: DramaTypeAgentState) -> dict:
    """Parse material into sections."""
    from app.agent.material_parser import parse_material_sections

    parsed = parse_material_sections(state["material_text"])
    return {"parsed_material": parsed}


def retrieve_knowledge_node(state: DramaTypeAgentState) -> dict:
    """Retrieve relevant knowledge from the knowledge base (RAG mode)."""
    from app.agent.rag_retriever import retrieve_knowledge

    mode = state.get("mode", "rule_based")
    if mode != "rag":
        return {"retrieved_context": "", "evidence_refs": []}

    # Build query from parsed material
    parsed = state.get("parsed_material", {})
    query_parts = []
    for key in ("basic_info", "characters", "nodes"):
        if key in parsed:
            query_parts.append(parsed[key])
    query = " ".join(query_parts) if query_parts else state.get("material_text", "")

    context, refs = retrieve_knowledge(query, top_k=8, use_vector=False)
    return {"retrieved_context": context, "evidence_refs": refs}


def generate_characters_node(state: DramaTypeAgentState) -> dict:
    """Generate character profiles."""
    mode = state.get("mode", "rule_based")
    parsed = state.get("parsed_material", {})

    if mode == "llm":
        from app.agent.langchain_generator import generate_content_pack_with_langchain
        cp = generate_content_pack_with_langchain(state.get("material_text", ""))
        return {"characters": cp.get("characters", [])}

    # rag or rule_based → use rule-based characters
    from app.agent.character_analyzer import analyze_characters
    characters = analyze_characters(parsed, mode="rule_based")
    return {"characters": characters}


def extract_nodes_node(state: DramaTypeAgentState) -> dict:
    """Extract narrative nodes."""
    mode = state.get("mode", "rule_based")
    parsed = state.get("parsed_material", {})

    if mode == "llm":
        return {}  # Already generated by langchain

    from app.agent.node_extractor import extract_narrative_nodes
    nodes = extract_narrative_nodes(parsed, mode="rule_based")
    return {"nodes": nodes}


def generate_questions_node(state: DramaTypeAgentState) -> dict:
    """Generate interactive questions."""
    mode = state.get("mode", "rule_based")

    if mode == "llm":
        return {}  # Already generated by langchain

    from app.agent.question_generator import generate_questions
    questions = generate_questions(
        state.get("nodes", []),
        state.get("characters", []),
        mode="rule_based",
    )
    return {"questions": questions}


def attach_slice_candidates_node(state: DramaTypeAgentState) -> dict:
    """Ensure all options have complete slice candidates."""
    from app.agent.slice_matcher import attach_slice_candidates

    questions = attach_slice_candidates(
        state.get("questions", []),
        state.get("nodes", []),
    )
    return {"questions": questions}


def generate_results_node(state: DramaTypeAgentState) -> dict:
    """Generate result profiles."""
    mode = state.get("mode", "rule_based")

    if mode == "llm":
        return {}  # Already generated by langchain

    from app.agent.result_generator import generate_results
    results = generate_results(state.get("characters", []), mode="rule_based")
    return {"results": results}


def review_safety_node(state: DramaTypeAgentState) -> dict:
    """Run safety review on the content pack."""
    from app.agent.safety_reviewer import review_content_pack

    # Build a temp content pack for review
    temp_pack = {
        "drama": {"title": "雾港来信", "type": "悬疑", "description": ""},
        "characters": state.get("characters", []),
        "nodes": state.get("nodes", []),
        "questions": state.get("questions", []),
        "results": state.get("results", []),
    }
    review = review_content_pack(temp_pack)
    return {"review": review}


def assemble_content_pack_node(state: DramaTypeAgentState) -> dict:
    """Assemble all pieces into the final content pack."""
    from app.core.config import settings

    review = state.get("review", {})

    content_pack = {
        "drama": {
            "title": "雾港来信",
            "type": "悬疑 / 群像 / 情感抉择 / 6集短剧",
            "description": "十年前，雾港发生一起未解旧案。十年后，一封没有署名的来信寄到四位故人手中。每个人都知道一部分真相，也都在隐瞒一部分过去。随着调查深入，他们必须在保护关系、追求真相、遵守规则和打破僵局之间做出选择。",
        },
        "characters": state.get("characters", []),
        "nodes": state.get("nodes", []),
        "questions": state.get("questions", []),
        "results": state.get("results", []),
        "review": review,
        "agent_meta": {
            "input_material_length": len(state.get("material_text", "")),
            "pipeline_version": "0.2.0",
            "generation_mode": state.get("mode", "rule_based"),
            "llm_provider": settings.LLM_PROVIDER if state.get("mode") == "llm" else None,
            "schema_validated": False,
            "human_review_required": True,
            "note": "AI 生成初稿，需运营审核后发布。",
        },
    }

    # Attach evidence_refs if RAG mode
    evidence_refs = state.get("evidence_refs", [])
    if evidence_refs:
        content_pack["agent_meta"]["note"] += f" RAG 检索证据 {len(evidence_refs)} 条。"

    return {"content_pack": content_pack}


def validate_content_pack_node(state: DramaTypeAgentState) -> dict:
    """Validate the content pack with Pydantic and JSON Schema."""
    from app.agent.schema_validator import validate_content_pack

    cp = state.get("content_pack", {})
    try:
        validate_content_pack(cp)
        cp["agent_meta"]["schema_validated"] = True
        return {"content_pack": cp, "validation_errors": []}
    except Exception as exc:
        return {"validation_errors": [str(exc)]}


def save_content_pack_node(state: DramaTypeAgentState) -> dict:
    """Save the content pack to disk."""
    from app.core.paths import DEFAULT_OUTPUT_PATH

    cp = state.get("content_pack", {})
    output_path = DEFAULT_OUTPUT_PATH

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(cp, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return {"output_path": str(output_path)}


# ── Build graph ────────────────────────────────────────

def build_graph():
    """
    Build the DramaType Agent LangGraph workflow.

    Returns a compiled graph that can be invoked with a DramaTypeAgentState.
    """
    try:
        from langgraph.graph import StateGraph, END
    except ImportError:
        raise ImportError(
            "langgraph is not installed. Run: pip install langgraph"
        )

    workflow = StateGraph(DramaTypeAgentState)

    # Add nodes
    workflow.add_node("read_material", read_material_node)
    workflow.add_node("parse_material", parse_material_node)
    workflow.add_node("retrieve_knowledge", retrieve_knowledge_node)
    workflow.add_node("generate_characters", generate_characters_node)
    workflow.add_node("extract_nodes", extract_nodes_node)
    workflow.add_node("generate_questions", generate_questions_node)
    workflow.add_node("attach_slice_candidates", attach_slice_candidates_node)
    workflow.add_node("generate_results", generate_results_node)
    workflow.add_node("review_safety", review_safety_node)
    workflow.add_node("assemble_content_pack", assemble_content_pack_node)
    workflow.add_node("validate_content_pack", validate_content_pack_node)
    workflow.add_node("save_content_pack", save_content_pack_node)

    # Define edges (linear flow)
    workflow.set_entry_point("read_material")
    workflow.add_edge("read_material", "parse_material")
    workflow.add_edge("parse_material", "retrieve_knowledge")
    workflow.add_edge("retrieve_knowledge", "generate_characters")
    workflow.add_edge("generate_characters", "extract_nodes")
    workflow.add_edge("extract_nodes", "generate_questions")
    workflow.add_edge("generate_questions", "attach_slice_candidates")
    workflow.add_edge("attach_slice_candidates", "generate_results")
    workflow.add_edge("generate_results", "review_safety")
    workflow.add_edge("review_safety", "assemble_content_pack")
    workflow.add_edge("assemble_content_pack", "validate_content_pack")
    workflow.add_edge("validate_content_pack", "save_content_pack")
    workflow.add_edge("save_content_pack", END)

    return workflow.compile()


def run_graph_pipeline(mode: str = "rule_based") -> dict:
    """
    Run the full LangGraph pipeline.

    Args:
        mode: "rule_based", "llm", or "rag"

    Returns:
        The final state with content_pack.
    """
    graph = build_graph()

    initial_state: DramaTypeAgentState = {
        "mode": mode,
        "validation_errors": [],
        "evidence_refs": [],
    }

    final_state = graph.invoke(initial_state)

    # Return the content_pack
    return final_state.get("content_pack", {})
